#!/bin/sh

exclude_branches="master|main"

while [ "$1" != "" ]; do
    case "$1" in
        --not)
            exclude_branches="$exclude_branches|$2"
            shift
            ;;
        *)
            echo "Error: Unknown option $1"
            exit 1
            ;;
    esac
    shift
done

BRANCHES=$(git branch | grep -E -v "($exclude_branches\*)" | sed 's/^+* * //' | tr '\n' ' ')

if [[ -z "$BRANCHES" ]]
then
    echo "No branches to delete."
    exit 0
fi

echo -e "${BRANCHES// /\n}"

read -p "Delete these branches [Yy/Nn] ? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    echo "$BRANCHES" | tr ' ' '\0' | xargs -0 -I {} git branch -D {}
fi
